INSERT INTO users (username, password, edit_all_permission) VALUES ('admin', 'ECLed!t1', TRUE);

INSERT INTO songs (song_title, band_name, genre, song_quote, recommend_why, user_id) VALUES ('I Don''t Live Here Anymore', 'The War On Drugs', 'Alternative/Indie', 'I''m gonna make it to the place I need to go. We''re all just walking through this darkness on our own!', 'This song is awesome! Rad synth, meaningful lyrics, 80s influence! So good!', 1);
INSERT INTO songs (song_title, band_name, genre, song_quote, recommend_why, user_id) VALUES ('Stupid Horse', '100 Gecs', 'Hyperpop', 'Stupid horse, I just fell out of the Porsche. Lost the money in my bank account, oh no.', '100 Gecs is ICONIC and no song personifies their fun weirdness like this song!', 1);
INSERT INTO songs (song_title, band_name, genre, song_quote, recommend_why, user_id) VALUES ('Will Anybody Ever Love Me?', 'Sufjan Stevens', 'Indie Folk', 'Will anybody ever love me? For good reasons, Without grievance, not for sport.', 'A song about losing the love of your life and questioning if life goes on or does it end here. An all time favorite', 1);
INSERT INTO songs (song_title, band_name, genre, song_quote, recommend_why, user_id) VALUES ('Flesh Without Blood', 'Grimes', 'Dance/ Electronic', 'It''s nice that you say you like me (you like me), But only conditionally.', 'SO MUCH FUN! Fantastic beat and both pretty and eerie at the same time!', 1);
INSERT INTO songs (song_title, band_name, genre, song_quote, recommend_why, user_id) VALUES ('Such Great Heights', 'The Postal Service', 'Indie Electropop', 'They will see us waving from such great heights Come down now, they''ll say. But everything looks perfect from far away, Come down now but we''ll stay.', 'This song is timeless and will never be out of my rotation!', 1);
INSERT INTO songs (song_title, band_name, genre, song_quote, recommend_why, user_id) VALUES ('How Much A Doller Cost', 'Kendrick Lamar', 'Rap', 'Shades of grey will never change if I condone. Turn this page, help me change, to right my wrongs.', 'The story in this song is one every person needs to hear. 10/10', 1);
INSERT INTO songs (song_title, band_name, genre, song_quote, recommend_why, user_id) VALUES ('Chaeri', 'Magdalena Bay', 'Synth-Pop', 'Forget the way things could''ve been. Did I learn anything? It was only that bad with you.', 'The dark synth and Y2k vibes are so right here, Check it out!', 1);
INSERT INTO songs (song_title, band_name, genre, song_quote, recommend_why, user_id) VALUES ('Walkin', 'Denzel Curry', 'Rap', 'I see the way the people get treated, it''s problematic. They ready to save themself for failure, it''s systematic. But when I felt it, my eyes melted', 'Denzel is the man! Amazing song. Go Listen.', 1);
INSERT INTO songs (song_title, band_name, genre, song_quote, recommend_why, user_id) VALUES ('The Place Where He Inserted The Blade', 'Black Country, New Road', 'Alternative/Indie', 'Oh, that every time I try to make lunch for anyone else, in my head I end up dreaming of you, And you come to me', 'Good Morning! Show me the place where this song is bad? You won''t find it!', 1);
INSERT INTO songs (song_title, band_name, genre, song_quote, recommend_why, user_id) VALUES ('Posing In Bondage', 'Japanese Breakfast', 'Indie Pop', 'Closeness, Proximity, I needed, Bondage', 'A sexy tune about wanting. Michelle really shows another side of herself here.', 1);